M darray
georust/gdal pull request #233
Opened 2021-11-18 05:52 UTC by geohardtke

- [x ] I agree to follow the project's [code of conduct](https://github.com/georust/gdal/blob/master/CODE_OF_CONDUCT.md).
- [ ] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---

Work in progress to add support for Multidimensional arrays.

resolves#232

2021-11-18 06:16 UTC, geohardtke commented
I see ci jobs are failing. The problem is ubuntu 20.04 ships with `gdal 3.0.4`, which doesn't include the Multidimensional array API. Can the ci be configured to grab a more modern version of gdal?

2021-11-18 11:07 UTC, jdroenner commented
you need to tag the your code to only be included with gdal >= 3.1 you can do that with something like this:
#[cfg(all(major_ge_3, minor_ge_1))]

we should add another ubunti version with a more modern gdal to the ci. i will look into that.

2021-11-18 23:29 UTC, geohardtke commented
> we should add another ubunti version with a more modern gdal to the ci. i will look into that.

Maybe you could set up a pipeline against each of the supported version (versions with pre-built bindings) of gdal. There are several versions available (>2.4) in dockerhub  https://hub.docker.com/r/osgeo/gdal

I'm happy to help with this as well.

2021-11-19 08:53 UTC, jdroenner commented
i'm always open to suggestions. Feel free to add ideas for the ci extension as new issue or pr :)

2021-11-22 00:36 UTC, geohardtke commented
> i'm always open to suggestions. Feel free to add ideas for the ci extension as new issue or pr :)

See https://github.com/georust/gdal/pull/234 

Some test are failing though any idea how to fix them?

2022-01-21 07:15 UTC, ChristianBeilschmidt requested changes
Thanks for the work!

Since I've been trying to use the multi-dimensional API from GDAL recently, I have a little experience to at least give you a first PR for this.

I've spotted some things and asked some questions. We have to be especially careful with memory handling where GDAL expects us to free things.

2022-01-21 07:15 UTC, ChristianBeilschmidt commented on src/raster/mdarray.rs
> +            let c_dimensions = GDALMDArrayGetDimensions(self.c_mdarray, pn_count_ptr);
> The returned array must be freed with GDALReleaseDimensions(). If only the array itself needs to be freed, CPLFree() should be called (and GDALDimensionRelease() on individual array members).

Do we account for that somewhere? I guess we need to call it when dropping a dimension and here, we need to free the array?

2022-01-21 07:15 UTC, ChristianBeilschmidt commented on src/raster/mdarray.rs
> +        // break on ndims not is_null
Maybe you can rephrase this: This breaks if the number of dimensions is not null?

2022-01-21 07:15 UTC, ChristianBeilschmidt commented on src/raster/mdarray.rs
> +            // }
If there is no possibility of a null pointer, you can remove it. Otherwise, we should integrate it.

2022-01-21 07:15 UTC, ChristianBeilschmidt commented on src/raster/mdarray.rs
> +                i += 1;
looks like a `for i in 0..n_dimension` loop

2022-01-21 07:15 UTC, ChristianBeilschmidt commented on src/raster/mdarray.rs
> +                let next = ptr.read();
Do you have to check for null-pointers here?

Maybe you can create a helper function that is similar to `_string_array`, just for Dimensions

2022-01-21 07:15 UTC, ChristianBeilschmidt commented on src/raster/mdarray.rs
> +    pub fn read_into_slice<T: Copy + GdalType>(
Maybe you can add some docs or copy some docs from the original documentation to understand the params.

2022-01-21 07:15 UTC, ChristianBeilschmidt commented on src/raster/mdarray.rs
> +        // let count =  [count.0, count.1];
```suggestion
```

2022-01-21 07:15 UTC, ChristianBeilschmidt commented on src/raster/mdarray.rs
> +        let buffer_stride: *const i64 = std::ptr::null();
Maybe add a comment that this means using defaults, e.g. [1, …] for the steps.

2022-01-21 07:15 UTC, ChristianBeilschmidt commented on src/raster/mdarray.rs
> +                p_dst_buffer_alloc_start,           // pDstBufferAllocStart: *const libc::c_void,
```suggestion
                buffer.as_mut_ptr() as *mut c_void,
                p_dst_buffer_alloc_start,
```

2022-01-21 07:15 UTC, ChristianBeilschmidt commented on src/raster/mdarray.rs
> +        }
What are your thoughts on this one? Maybe we can help getting this correct.

2022-01-21 07:15 UTC, ChristianBeilschmidt commented on src/raster/mdarray.rs
> +        self.read_into_slice(&mut data, array_start_index, count)?;
In the example, they read into the array-ptr and then set the length. Does that make any difference?

2022-01-21 07:15 UTC, ChristianBeilschmidt commented on src/raster/mdarray.rs
> +/// Represent a mdarray in a dataset
```suggestion
/// Represent a `Group` in a `Dataset`
```

2022-01-21 07:15 UTC, ChristianBeilschmidt commented on src/raster/mdarray.rs
> +            unsafe { GDALGroupOpenMDArray(self.c_group, name.as_ptr(), options.as_ptr()) };
> Returns    the array names, to be freed with CSLDestroy()

Do we do this somewhere?

I guess @jdroenner used valgrind at some point. Maybe we can do this here. I also struggle to get these C-calls and frees right, so maybe this helps spotting errors.

2022-01-21 07:15 UTC, ChristianBeilschmidt commented on src/raster/mdarray.rs
> +    // }
```suggestion
```

2022-01-26 13:35 UTC, jdroenner commented
@geohardtke  are you still working on this? we merged the 3.4 integration.

2022-02-08 23:26 UTC, geohardtke commented
Hi @jdroenner  and @ChristianBeilschmidt. Thanks for having a look. I'll try to smooth the rough edges a bit and update the branch.

2022-05-19 14:41 UTC, closed without merging

2022-05-19 14:42 UTC, jdroenner commented
closed this PR and merged 273